env:
  es6: true
  mocha: true
  node: true
extends:
  - eslint:recommended
  - prettier
parserOptions:
  ecmaVersion: 9
plugins:
  - prettier
rules:
  no-var: error
  prefer-const: error
  prettier/prettier: error
  quotes:
    - error
    - single
    - avoidEscape: true
