env:
  es6: true
  mocha: true
  node: true
extends:
  - eslint:recommended
  - plugin:prettier/recommended
parserOptions:
  ecmaVersion: latest
rules:
  no-var: error
  prefer-const: error
  quotes:
    - error
    - single
    - avoidEscape: true
