// Generated by CoffeeScript 1.10.0
(function() {
  var Article, BaseChild, Metafields,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseChild = require('./base_child');

  Metafields = require('./metafield');

  Article = (function(superClass) {
    extend(Article, superClass);

    Article.prototype.parent = "/blogs";

    Article.prototype.slug = "article";

    Article.prototype.child = "/articles";

    function Article(site) {
      Article.__super__.constructor.call(this, site);
    }

    return Article;

  })(BaseChild);

  module.exports = Article;

}).call(this);
