// Generated by CoffeeScript 1.10.0
(function() {
  var BaseChild, pluralize;

  pluralize = require('pluralize');

  BaseChild = (function() {
    BaseChild.prototype.parent = "/parent";

    BaseChild.prototype.slug = "base";

    BaseChild.prototype.child = "/base";

    BaseChild.prototype.resource = require('../resource');

    function BaseChild(site) {
      this.site = site;
      this.prefix = "" + site + this.parent;
    }

    BaseChild.prototype.all = function(parentId, params, callback) {
      var pluralizedSlug, ref, url;
      if (typeof params === 'function') {
        ref = [callback, params], params = ref[0], callback = ref[1];
      }
      url = this.resource.queryString(this.prefix + "/" + parentId + this.child, params);
      pluralizedSlug = pluralize(this.slug);
      return this.resource.get(url, pluralizedSlug, callback);
    };

    BaseChild.prototype.count = function(parentId, params, callback) {
      var ref, url;
      if (typeof params === 'function') {
        ref = [callback, params], params = ref[0], callback = ref[1];
      }
      url = this.resource.queryString(this.prefix + "/" + parentId + this.child + "/count", params);
      return this.resource.get(url, "count", callback);
    };

    BaseChild.prototype.get = function(parentId, id, params, callback) {
      var ref, url;
      if (typeof params === 'function') {
        ref = [callback, params], params = ref[0], callback = ref[1];
      }
      if (id == null) {
        callback(new Error('missing id'));
      }
      url = this.resource.queryString(this.prefix + "/" + parentId + this.child + "/" + id, params);
      return this.resource.get(url, this.slug, callback);
    };

    BaseChild.prototype.create = function(parentId, fields, callback) {
      var url;
      url = this.resource.queryString(this.prefix + "/" + parentId + this.child);
      return this.resource.post(url, this.slug, fields, callback);
    };

    BaseChild.prototype.update = function(parentId, id, fields, callback) {
      var url;
      if (id == null) {
        callback(new Error('missing id'));
      }
      url = this.resource.queryString(this.prefix + "/" + parentId + this.child + "/" + id);
      return this.resource.put(url, this.slug, fields, callback);
    };

    BaseChild.prototype["delete"] = function(parentId, id, callback) {
      var url;
      if (id == null) {
        callback(new Error('missing'));
      }
      url = this.resource.queryString(this.prefix + "/" + parentId + this.child + "/" + id);
      return this.resource["delete"](url, id, callback);
    };

    return BaseChild;

  })();

  module.exports = BaseChild;

}).call(this);
