// Generated by CoffeeScript 1.10.0
(function() {
  var Base, CarrierService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  CarrierService = (function(superClass) {
    extend(CarrierService, superClass);

    CarrierService.prototype.slug = "carrier_service";

    CarrierService.prototype.prefix = "/carrier_services";

    function CarrierService(site) {
      CarrierService.__super__.constructor.call(this, site);
    }

    return CarrierService;

  })(Base);

  module.exports = CarrierService;

}).call(this);
