// Generated by CoffeeScript 1.10.0
(function() {
  var Base, Country,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  Country = (function(superClass) {
    extend(Country, superClass);

    Country.prototype.slug = "country";

    Country.prototype.prefix = "/countries";

    function Country(site) {
      Country.__super__.constructor.call(this, site);
    }

    Country.prototype.all = function(params, callback) {
      var ref, url;
      if (typeof params === 'function') {
        ref = [callback, params], params = ref[0], callback = ref[1];
      }
      url = this.resource.queryString(this.prefix, params);
      return this.resource.get(url, "countries", callback);
    };

    return Country;

  })(Base);

  module.exports = Country;

}).call(this);
