// Generated by CoffeeScript 1.10.0
(function() {
  var Base, CustomerSavedSearch,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  CustomerSavedSearch = (function(superClass) {
    extend(CustomerSavedSearch, superClass);

    CustomerSavedSearch.prototype.slug = "customer_saved_search";

    CustomerSavedSearch.prototype.prefix = "/customer_saved_searches";

    function CustomerSavedSearch(site) {
      CustomerSavedSearch.__super__.constructor.call(this, site);
    }

    CustomerSavedSearch.prototype.all = function(params, callback) {
      var ref, url;
      if (typeof params === 'function') {
        ref = [callback, params], params = ref[0], callback = ref[1];
      }
      url = this.resource.queryString(this.prefix, params);
      return this.resource.get(url, "customer_saved_searches", callback);
    };

    CustomerSavedSearch.prototype.getCustomersForId = function(id, callback) {
      var url;
      if (id == null) {
        callback(new Error('missing id'));
      }
      url = this.resource.queryString(this.prefix + "/" + id + "/customers");
      return this.resource.get(url, "customers", callback);
    };

    return CustomerSavedSearch;

  })(Base);

  module.exports = CustomerSavedSearch;

}).call(this);
