// Generated by CoffeeScript 1.10.0
(function() {
  var Base, Customer,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  Customer = (function(superClass) {
    extend(Customer, superClass);

    Customer.prototype.slug = "customer";

    Customer.prototype.prefix = "/customers";

    function Customer(site) {
      Customer.__super__.constructor.call(this, site);
    }

    return Customer;

  })(Base);

  module.exports = Customer;

}).call(this);
