// Generated by CoffeeScript 1.10.0
(function() {
  var Base, Customer, pluralize,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  pluralize = require('pluralize');

  Base = require('./base');

  Customer = (function(superClass) {
    extend(Customer, superClass);

    Customer.prototype.slug = 'customer';

    Customer.prototype.prefix = '/customers';

    function Customer(site) {
      Customer.__super__.constructor.call(this, site);
    }

    Customer.prototype.search = function(params, callback) {
      var url;
      url = this.resource.queryString(this.prefix + "/search", params);
      return this.resource.get(url, pluralize(this.slug), callback);
    };

    Customer.prototype.createActivationUrl = function(id, callback) {
      var slug, url;
      url = this.resource.queryString(this.prefix + "/" + id + "/account_activation_url");
      slug = {
        short: this.slug,
        long: 'account_activation_url'
      };
      return this.resource.post(url, slug, {
        id: id
      }, callback);
    };

    return Customer;

  })(Base);

  module.exports = Customer;

}).call(this);
