// Generated by CoffeeScript 1.10.0
(function() {
  var Base, CustomCollection,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  CustomCollection = (function(superClass) {
    extend(CustomCollection, superClass);

    CustomCollection.prototype.slug = "custom_collection";

    CustomCollection.prototype.prefix = "/custom_collections";

    function CustomCollection(site) {
      CustomCollection.__super__.constructor.call(this, site);
    }

    return CustomCollection;

  })(Base);

  module.exports = CustomCollection;

}).call(this);
