// Generated by CoffeeScript 1.10.0
(function() {
  var Base, Event,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  Event = (function(superClass) {
    extend(Event, superClass);

    Event.prototype.slug = "event";

    Event.prototype.prefix = "/events";

    function Event(site) {
      Event.__super__.constructor.call(this, site);
    }

    return Event;

  })(Base);

  module.exports = Event;

}).call(this);
