// Generated by CoffeeScript 1.10.0
(function() {
  var Base, FulfillmentService,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  FulfillmentService = (function(superClass) {
    extend(FulfillmentService, superClass);

    FulfillmentService.prototype.slug = "fulfillment_service";

    FulfillmentService.prototype.prefix = "/fulfillment_services";

    function FulfillmentService(site) {
      FulfillmentService.__super__.constructor.call(this, site);
    }

    return FulfillmentService;

  })(Base);

  module.exports = FulfillmentService;

}).call(this);
