// Generated by CoffeeScript 1.10.0
(function() {
  var Base, GiftCard,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  GiftCard = (function(superClass) {
    extend(GiftCard, superClass);

    GiftCard.prototype.slug = 'gift_card';

    GiftCard.prototype.prefix = '/gift_cards';

    function GiftCard(site) {
      GiftCard.__super__.constructor.call(this, site);
    }

    GiftCard.prototype.getAll = function(callback) {
      return this.all(callback);
    };

    GiftCard.prototype.checkValidStatus = function(status, callback) {
      if (!~["disabled", "enabled"].indexOf(status)) {
        return callback(new Error('status is not valid'));
      }
    };

    GiftCard.prototype.getByStatus = function(status, callback) {
      this.checkValidStatus(status, callback);
      return this.all({
        status: status
      }, callback);
    };

    GiftCard.prototype.getCount = function(callback) {
      return this.count(void 0, callback);
    };

    GiftCard.prototype.getCountByStatus = function(status, callback) {
      this.checkValidStatus(status, callback);
      return this.count({
        status: status
      }, callback);
    };

    return GiftCard;

  })(Base);

  module.exports = GiftCard;

}).call(this);

//# sourceMappingURL=gift_card.js.map
