// Generated by CoffeeScript 1.10.0
(function() {
  var Base, Location,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  Location = (function(superClass) {
    extend(Location, superClass);

    Location.prototype.slug = "location";

    Location.prototype.prefix = "/locations";

    function Location(site) {
      Location.__super__.constructor.call(this, site);
    }

    return Location;

  })(Base);

  module.exports = Location;

}).call(this);
