// Generated by CoffeeScript 1.10.0
(function() {
  var Base, Metafields, Page,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  Metafields = require('./metafield');

  Page = (function(superClass) {
    extend(Page, superClass);

    Page.prototype.slug = "page";

    Page.prototype.prefix = "/pages";

    function Page(site) {
      this.metafields = new Metafields(this.prefix, site);
      Page.__super__.constructor.call(this, site);
    }

    Page.prototype.events = function(id, params, callback) {
      var ref, url;
      if (typeof params === 'function') {
        ref = [callback, params], params = ref[0], callback = ref[1];
      }
      if (id == null) {
        callback(new Error('missing id'));
      }
      url = this.resource.queryString(this.prefix + "/" + id + "/events", params);
      return this.resource.get(url, "events", callback);
    };

    return Page;

  })(Base);

  module.exports = Page;

}).call(this);
