// Generated by CoffeeScript 1.10.0
(function() {
  var Base, Policy,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  Policy = (function(superClass) {
    extend(Policy, superClass);

    Policy.prototype.slug = 'policy';

    Policy.prototype.prefix = '/policies';

    function Policy(site) {
      Policy.__super__.constructor.call(this, site);
    }

    return Policy;

  })(Base);

  module.exports = Policy;

}).call(this);
