// Generated by CoffeeScript 1.10.0
(function() {
  var BaseChild, Metafields, ProductImage,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseChild = require('./base_child');

  Metafields = require('./metafield');

  ProductImage = (function(superClass) {
    extend(ProductImage, superClass);

    ProductImage.prototype.parent = "/products";

    ProductImage.prototype.slug = "image";

    ProductImage.prototype.child = "/images";

    function ProductImage(site) {
      ProductImage.__super__.constructor.call(this, site);
    }

    return ProductImage;

  })(BaseChild);

  module.exports = ProductImage;

}).call(this);
