// Generated by CoffeeScript 1.10.0
(function() {
  var Base, Metafields, Product,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  Metafields = require('./metafield');

  Product = (function(superClass) {
    extend(Product, superClass);

    Product.prototype.slug = "product";

    Product.prototype.prefix = "/products";

    function Product(site) {
      this.metafields = new Metafields(this.prefix, site);
      Product.__super__.constructor.call(this, site);
    }

    Product.prototype.events = function(id, params, callback) {
      var ref, url;
      if (typeof params === 'function') {
        ref = [callback, params], params = ref[0], callback = ref[1];
      }
      if (id == null) {
        callback(new Error('missing id'));
      }
      url = this.resource.queryString(this.prefix + "/" + id + "/events", params);
      return this.resource.get(url, "events", callback);
    };

    return Product;

  })(Base);

  module.exports = Product;

}).call(this);
