// Generated by CoffeeScript 1.10.0
(function() {
  var BaseChild, Metafields, Province,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseChild = require('./base_child');

  Metafields = require('./metafield');

  Province = (function(superClass) {
    extend(Province, superClass);

    Province.prototype.parent = "/countries";

    Province.prototype.slug = "province";

    Province.prototype.child = "/provinces";

    function Province(site) {
      Province.__super__.constructor.call(this, site);
    }

    return Province;

  })(BaseChild);

  module.exports = Province;

}).call(this);
