// Generated by CoffeeScript 1.10.0
(function() {
  var Base, ScriptTag,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  ScriptTag = (function(superClass) {
    extend(ScriptTag, superClass);

    ScriptTag.prototype.slug = "script_tag";

    ScriptTag.prototype.prefix = "/script_tags";

    function ScriptTag(site) {
      ScriptTag.__super__.constructor.call(this, site);
    }

    return ScriptTag;

  })(Base);

  module.exports = ScriptTag;

}).call(this);
