// Generated by CoffeeScript 1.10.0
(function() {
  var Base, ShippingZone,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  ShippingZone = (function(superClass) {
    extend(ShippingZone, superClass);

    ShippingZone.prototype.slug = 'shipping_zone';

    ShippingZone.prototype.prefix = '/shipping_zones';

    function ShippingZone(site) {
      ShippingZone.__super__.constructor.call(this, site);
    }

    return ShippingZone;

  })(Base);

  module.exports = ShippingZone;

}).call(this);
