// Generated by CoffeeScript 1.10.0
(function() {
  var Base, SmartCollection,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  SmartCollection = (function(superClass) {
    extend(SmartCollection, superClass);

    SmartCollection.prototype.slug = 'smart_collection';

    SmartCollection.prototype.prefix = '/smart_collections';

    function SmartCollection(site) {
      SmartCollection.__super__.constructor.call(this, site);
    }

    SmartCollection.prototype.order = function(id, params, callback) {
      var ref, url;
      if (typeof params === 'function') {
        ref = [callback, params], params = ref[0], callback = ref[1];
      }
      url = this.resource.queryString(this.prefix + "/" + id + "/order", params);
      return this.resource.put(url, void 0, {}, callback);
    };

    return SmartCollection;

  })(Base);

  module.exports = SmartCollection;

}).call(this);
