// Generated by CoffeeScript 1.10.0
(function() {
  var Base, Theme,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  Theme = (function(superClass) {
    extend(Theme, superClass);

    Theme.prototype.slug = "theme";

    Theme.prototype.prefix = "/themes";

    function Theme(site) {
      Theme.__super__.constructor.call(this, site);
    }

    return Theme;

  })(Base);

  module.exports = Theme;

}).call(this);
