// Generated by CoffeeScript 1.10.0
(function() {
  var BaseChild, Transaction,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  BaseChild = require('./base_child');

  Transaction = (function(superClass) {
    extend(Transaction, superClass);

    Transaction.prototype.parent = "/orders";

    Transaction.prototype.slug = "transaction";

    Transaction.prototype.child = "/transactions";

    function Transaction(site) {
      Transaction.__super__.constructor.call(this, site);
    }

    return Transaction;

  })(BaseChild);

  module.exports = Transaction;

}).call(this);
