// Generated by CoffeeScript 1.10.0
(function() {
  var Base, User,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  Base = require('./base');

  User = (function(superClass) {
    extend(User, superClass);

    User.prototype.slug = "user";

    User.prototype.prefix = "/users";

    function User(site) {
      User.__super__.constructor.call(this, site);
    }

    return User;

  })(Base);

  module.exports = User;

}).call(this);
