// Generated by CoffeeScript 1.10.0
(function() {
  var AuthSession, Session;

  AuthSession = require('./session-oauth');

  Session = require('./session');

  exports.createSession = function(storename, apiKey, secret, params) {
    return new AuthSession(storename, apiKey, secret, params);
  };

  exports.createPrivateAppSession = function(storename, apiKey, password, params) {
    return new Session(storename, apiKey, password, params);
  };

}).call(this);
